# EXCEPTION IS KIND OF ERROR THAT CRASH THE SERVER SO TO PREVENT DO THIS:
try:
   age = int(input('age: '))
   income = 20000
   risk = income/age
# IF WE PUT AGE AS ZERO THEN THERE IS ANOTHER ERROR 'ZERDIVISIONERROR'
   print(risk)
except ValueError and ZeroDivisionError:
        print('Invalid Value')

# WE ARE TELLING THE INTERPRATOR THAT IF HE ENCOUNTERED ANY ERROR NAME 'VALUEERROR'.
# THEN INSTEAD OF CRASHING THE CODE JUST RUN THE CODE IN EXCEPT.



